displays if filters are selected in sidebar
LDMW/app pull request #283
Opened 2017-06-02 12:55 UTC by Danwhy

ref #263
Displays the name of the tag if only one is selected, or the number of tags if multiple are selected

2017-06-02 13:10 UTC, samhstn requested changes
Not to sure about the above btw, could you clarify.

Otherwise, looks great

2017-06-02 13:10 UTC, shouston3 commented on web/static/js/sidebar.js
> +  for (var value of formData.entries()) {
Not too sure about the browser compatibility of `for... of` loops. Couldn't find info on MDN or CanIUse, but [here](https://docs.microsoft.com/en-us/scripting/javascript/reference/for-dot-dot-dot-of-statement-javascript) it says `Not supported in the following document modes... Internet Explorer 8 standards, Internet Explorer 9 standards, Internet Explorer 10 standards`

I'm a little unclear how supported this is tbh. You could probably write something similar with a `for` loop or `for...in` loop or something.

2017-06-02 14:36 UTC, samhstn approved these changes
Looks great

2017-06-05 14:51 UTC, nelsonic approved these changes
@Danwhy great work. 🎉

2017-06-06 07:50 UTC, SimonLab approved these changes
Looks good :+1: , elm :wink: ?

2017-06-06 07:50 UTC, merged