Editable Content from CMS
LDMW/app pull request #301
Opened 2017-06-06 16:28 UTC by Danwhy

2017-06-07 13:26 UTC, samhstn requested changes
Looks great after that small change

2017-06-07 13:26 UTC, shouston3 commented on test/controllers/banner_test.exs
> +  doctest App.Banner
Very minor point, but could we have `import: true` here (for consistency)

2017-06-07 13:26 UTC, shouston3 commented on web/controllers/banner.ex
> +    true
And then make this:
```elixir
iex> init(true)
true
```

2017-06-07 13:34 UTC, samhstn approved these changes
Looks great 👍

2017-06-08 09:46 UTC, SimonLab approved these changes
LGTM :+1:

2017-06-08 09:46 UTC, merged