fix issues raised in #417
LDMW/app pull request #421
Opened 2017-06-26 15:10 UTC by shouston3

2017-06-26 18:12 UTC, iteles commented
Linked to #386

2017-06-26 19:05 UTC, nelsonic approved these changes
@shouston3 👍

2017-06-27 07:04 UTC, SimonLab approved these changes
LGTM :+1:

2017-06-27 10:44 UTC, iteles requested changes
Thanks @shouston3, let's make the changes we discussed earlier today please 👍

2017-06-27 10:44 UTC, iteles commented on README.md
> +Also note that on mobile the hero image is cut off so please test your image on the [staging area](https://ldmw-cms-staging.herokuapp.com/admin)
@shouston3 As discussed, let's use different terminology here to explain it is working as expected and not a bug - something along the lines of using a one size fits all image means it is displayed in different ways on each form factor as we have specified that it needs to cover the full background of the text it contains.

Let's also:
+ Add an example screenshot to the documentation 
+ Centre the image on mobile

2017-06-27 11:00 UTC, shouston3 commented on README.md
> +Also note that on mobile the hero image is cut off so please test your image on the [staging area](https://ldmw-cms-staging.herokuapp.com/admin)
I've just centered the image for every device, I think it looks better (much better on mobile though)

2017-06-27 16:18 UTC, iteles approved these changes
LGTM

2017-06-27 16:18 UTC, merged